u"""Predefined message classes"""

from __future__ import absolute_import
from . import core

__all__ = [u'ACK_CLS', u'CFG_CLS', u'ESF_CLS', u'INF_CLS', u'MGA_CLS', u'MON_CLS',
           u'NAV_CLS', u'TIM_CLS', ]

ACK_CLS = core.Cls(0x05, u'ACK', [
    core.Message(0x01, u'ACK', [
        core.Field(u'clsID', u'U1'),
        core.Field(u'msgID', u'U1'),
    ]),
    core.Message(0x00, u'NAK', [
        core.Field(u'clsID', u'U1'),
        core.Field(u'msgID', u'U1'),
    ])
])

CFG_CLS = core.Cls(0x06, u'CFG', [
    core.Message(0x41, u'OTP', [
    ]),
    core.Message(0x1, u'MSG', [
        core.Field(u'msgClass', u'U1'),
        core.Field(u'msgID', u'U1'),
    ]),
    core.Message(0x2C, u'PIO', [
        core.Field(u'version', u'U1'),
        core.Field(u'request', u'U1'),
        core.RepeatedBlock(u'RB', [
            core.Field(u'requiredPinState', u'U1'),
        ])
    ]),
    core.Message(0x00, u'PRT', [
        core.Field(u'portID', u'U1'),
        core.PadByte(repeat=1),
        core.BitField(u'txReady', u'X2', [
            core.Flag(u'en', 0, 1),
            core.Flag(u'pol', 1, 2),
            core.Flag(u'pin', 2, 6),
            core.Flag(u'thres', 7, 16),
        ]),
        core.BitField(u'mode', u'X4', [
            core.Flag(u'charLen', 6, 8),
            core.Flag(u'parity', 9, 12),
            core.Flag(u'nStopBits', 12, 13),
        ]),
        core.Field(u'baudRate', u'U4'),
        core.BitField(u'inProtoMask', u'X2', [
            core.Flag(u'inUbx', 0, 1),
            core.Flag(u'inNmea', 1, 2),
            core.Flag(u'inRtcm', 2, 3),
            core.Flag(u'inRtcm3', 5, 6),
        ]),
        core.BitField(u'outProtoMask', u'X2', [
            core.Flag(u'outUbx', 0, 1),
            core.Flag(u'outNmea', 1, 2),
            core.Flag(u'outRtcm3', 5, 6),
        ]),
        core.BitField(u'flags', u'X2', [
            core.Flag(u'extendedTxTimeout', 0, 1),
        ]),
        core.PadByte(repeat=2)
    ]),
    core.Message(0x59, u'PT2', [
        core.Field(u'version', u'U1'),
        core.BitField(u'activate', u'X1', [
            core.Flag(u'enable', 0, 1),
            core.Flag(u'lnaMode', 6, 8),
        ]),
        core.Field(u'extint', u'U1'),
        core.Field(u'reAcqCno', u'U1'),
        core.Field(u'refFreq', u'U4'),
        core.Field(u'refFreqAcc', u'U4'),
        core.RepeatedBlock(u'RB', [
            core.Field(u'gnssId', u'U1'),
            core.Field(u'svId', u'U1'),
            core.Field(u'sigId', u'U1'),
            core.Field(u'accsId', u'U1'),
        ])
    ]),
    core.Message(0x04, u'RST', [
        core.BitField(u'navBbrMask', u'X2', [
            core.Flag(u'eph', 0, 1),
            core.Flag(u'alm', 1, 2),
            core.Flag(u'health', 2, 3),
            core.Flag(u'klob', 3, 4),
            core.Flag(u'pos', 4, 5),
            core.Flag(u'clkd', 5, 6),
            core.Flag(u'osc', 6, 7),
            core.Flag(u'utc', 7, 8),
            core.Flag(u'rtc', 8, 9),
            core.Flag(u'sfdr', 11, 12),
            core.Flag(u'vmon', 12, 13),
            core.Flag(u'tct', 13, 14),
            core.Flag(u'aop', 15, 16),
        ]),
        core.Field(u'resetMode', u'U1'),
        core.PadByte(repeat=1),
    ]),
    core.Message(0x64, u'SPT', [
        core.Field(u'version', u'U1'),
        core.PadByte(repeat=1),
        core.Field(u'sensorId', u'U2'),
        core.PadByte(repeat=8),
    ]),
    core.Message(0x58, u'USBTEST', [
        core.Field(u'version', u'U1'),
        core.Field(u'usbPinState', u'U1'),
    ]),
    core.Message(0x8c, u'VALDEL', [ # With transaction
        core.Field(u'version', u'U1'),
        core.Field(u'usbPinState', u'U1'),
        core.BitField(u'layers', u'X1', [
            core.Flag(u'bbr', 1, 2),
            core.Flag(u'flash', 2, 3),
        ]),
        core.PadByte(repeat=2),
        core.RepeatedBlock(u'RB', [
            core.Field(u'keys',u'U4'),
        ]),
    ]),
    core.Message(0x8b, u'VALGET', [ # Get configuration items
        core.Field(u'version', u'U1'),
        core.Field(u'layer', u'U1'),
        core.Field(u'position', u'U2'),
        core.RepeatedBlock(u'RB', [
            core.Field(u'cfgData',u'U1'),
        ]),
    ]),
    core.Message(0x8a, u'VALSET', [ # With Tranaction
        core.Field(u'version', u'U1'),
        core.BitField(u'layers', u'X1', [
            core.Flag(u'ram', 0, 1),
            core.Flag(u'bbr', 1, 2),
            core.Flag(u'flash', 2, 3),
        ]),
        core.Field(u'transaction', u'U1'),
        core.Field(u'action', u'U1'),
        core.PadByte(repeat=1),
        core.RepeatedBlock(u'RB', [
            core.Field(u'cfgData',u'U1'),
        ]),
    ]),
])

ESF_CLS = core.Cls(0x10, u'ESF', [
    core.Message(0x14, u'ALG', [
        core.Field(u'iTOW',u'U4'),
        core.Field(u'version',u'U1'),
        core.BitField(u'flags', u'X1', [
            core.Flag(u'autoMntAlgOn', 0, 1),
            core.Flag(u'status', 1, 4),
        ]),
        core.BitField(u'error', u'X1', [
            core.Flag(u'tiltAlgError', 0, 1),
            core.Flag(u'yawAlgoError', 1, 2),
            core.Flag(u'angleError', 2, 3),
        ]),
        core.PadByte(repeat=1),
        core.Field(u'yaw',u'U4'),
        core.Field(u'pitch',u'I2'),
        core.Field(u'roll',u'I2'),
    ]),
    core.Message(0x15, u'INS', [
        core.BitField(u'biltfield0', u'X4', [
            core.Flag(u'version', 0, 8),
            core.Flag(u'xAngRateValid', 8, 9),
            core.Flag(u'yAngRateValid', 9, 10),
            core.Flag(u'zAngRateValid', 10, 11),
            core.Flag(u'xAccelValid', 11, 12),
            core.Flag(u'yAccelValid', 12, 13),
            core.Flag(u'zAccelValid', 13, 14),
        ]),
        core.PadByte(repeat=3),
        core.Field(u'iTOW',u'U4'),
        core.Field(u'xAngRate',u'I4'),
        core.Field(u'yAngRate',u'I4'),
        core.Field(u'zAngRate',u'I4'),
        core.Field(u'xAccel',u'I4'),
        core.Field(u'yAccel',u'I4'),
        core.Field(u'zAccel',u'I4'),
    ]),
    core.Message(0x02, u'MEAS', [
        core.Field(u'timeTag',u'U4'),
        core.BitField(u'flags', u'X2', [
            core.Flag(u'timeMarkSent', 0, 2),
            core.Flag(u'timeMarkEdge', 2, 3),
            core.Flag(u'calibTtagValid', 3, 4),
            core.Flag(u'numMeas', 11, 16),
        ]),
        core.Field(u'id',u'U2'),
        core.RepeatedBlock(u'RB', [
            core.BitField(u'data',u'X4', [
                core.Flag(u'dataField', 0, 24),
                core.Flag(u'dataType', 24, 30),
            ]),
            core.Field(u'calibTtag',u'U4'),
        ]),
    ]),
    core.Message(0x03, u'RAW', [
        core.PadByte(repeat=4),
        core.RepeatedBlock(u'RB', [
            core.BitField(u'data',u'X4', [
                core.Flag(u'dataField', 0, 24),
                core.Flag(u'dataType', 24, 30),
            ]),
            core.Field(u'sTag',u'U4'),
        ]),
    ]),
    core.Message(0x13, u'RESETALG', [
    ]),
    core.Message(0x10, u'STATUS', [
        core.Field(u'iTOW',u'U4'),
        core.Field(u'version',u'U1'),
        core.BitField(u'initStatus1', u'X1', [
            core.Flag(u'wtInitStatus', 0, 2),
            core.Flag(u'mntAlgStatus', 2, 5),
            core.Flag(u'insInitStatus', 5, 7),
        ]),
        core.BitField(u'initStatus2', u'X1', [
            core.Flag(u'imuInitStatus', 0, 2),
        ]),
        core.PadByte(repeat=3),
        core.Field(u'fusionMode',u'U1'),
        core.PadByte(repeat=2),
        core.Field(u'numSens',u'U1'),
        core.RepeatedBlock(u'RB', [
            core.BitField(u'senStatus1', u'X1', [
                core.Flag(u'type', 0, 6),
                core.Flag(u'used', 6, 7),
                core.Flag(u'ready', 7, 8),
            ]),
            core.BitField(u'senStatus2', u'X1', [
                core.Flag(u'calibStatus', 0, 2),
                core.Flag(u'timeStatus', 2, 4),
            ]),
            core.Field(u'freq', u'U1'),
            core.BitField(u'faults', u'X1', [
                core.Flag(u'badMeas', 0, 1),
                core.Flag(u'badTTag', 1, 2),
                core.Flag(u'missingMeas', 2, 3),
                core.Flag(u'noisyMeas', 3, 4),
            ]),
        ]),
    ]),

])

INF_CLS = core.Cls(0x04, u'INF', [
    core.Message(0x04, u'DEBUG', [
        core.RepeatedBlock(u'RB', [
            core.Field(u'str',u'C'),
        ]),
    ]),
    core.Message(0x00, u'ERROR', [
        core.RepeatedBlock(u'RB', [
            core.Field(u'str',u'C'),
        ]),
    ]),
    core.Message(0x02, u'NOTICE', [
        core.RepeatedBlock(u'RB', [
            core.Field(u'str',u'C'),
        ]),
    ]),
    core.Message(0x03, u'TEST', [
        core.RepeatedBlock(u'RB', [
            core.Field(u'str',u'C'),
        ]),
    ]),
    core.Message(0x01, u'WARNING', [
        core.RepeatedBlock(u'RB', [
            core.Field(u'str',u'C'),
        ]),
    ]),
])

MGA_CLS = core.Cls(0x13, u'MGA', [
    core.Message(0x60, u'ACK', [
        core.Field(u'type', u'U1'),
        core.Field(u'version', u'U1'),
        core.Field(u'infoCode', u'U1'),
        core.Field(u'msgId', u'U1'),
        core.Field(u'msgPayloadStart', u'U1'),
    ]),
    core.Message(0x03, u'BDS_EPH', [
        core.Field(u'type', u'U1'),
        core.Field(u'version', u'U1'),
        core.Field(u'svId', u'U1'),
        core.PadByte(repeat=1),
        core.Field(u'SatH1', u'U1'),
        core.Field(u'IODC', u'U1'),
        core.Field(u'a2', u'I2'),
        core.Field(u'a1', u'I4'),
        core.Field(u'a0', u'I4'),
        core.Field(u'toc', u'U4'),
        core.Field(u'TGD1', u'I2'),
        core.Field(u'URAI', u'U1'),
        core.Field(u'IODE', u'U1'),
        core.Field(u'toe', u'U4'),
        core.Field(u'sqrtA', u'U4'),
        core.Field(u'e', u'U4'),
        core.Field(u'omega', u'I4'),
        core.Field(u'Deltan', u'I2'),
        core.Field(u'IDOT', u'I2'),
        core.Field(u'M0', u'I4'),
        core.Field(u'Omega0', u'I4'),
        core.Field(u'OmegaDot', u'I4'),
        core.Field(u'i0', u'I4'),
        core.Field(u'Cuc', u'I4'),
        core.Field(u'Cus', u'I4'),
        core.Field(u'Crc', u'I4'),
        core.Field(u'Crs', u'I4'),
        core.PadByte(repeat=4),
    ]), # Input
    core.Message(0x03, u'BDS_ALM', [
        core.Field(u'type', u'U1'),
        core.Field(u'version', u'U1'),
        core.Field(u'svId', u'U1'),
        core.PadByte(repeat=1),
        core.Field(u'Wna', u'U1'),
        core.Field(u'toa', u'U1'),
        core.Field(u'deltaI', u'I2'),
        core.Field(u'sqrtA', u'U4'),
        core.Field(u'omega', u'I4'),
        core.Field(u'M0', u'I4'),
        core.Field(u'Omega0', u'I4'),
        core.Field(u'OmegaDot', u'I4'),
        core.Field(u'a0', u'I4'),
        core.PadByte(repeat=4),
    ]), # Input
    core.Message(0x03, u'BDS_HEALTH', [
        core.Field(u'type', u'U1'),
        core.Field(u'version', u'U1'),
        core.PadByte(repeat=2),
        core.Field(u'healthCode', u'U2'),
        core.PadByte(repeat=4),
    ]), # Input
    core.Message(0x03, u'BDS_UTC', [
        core.Field(u'type', u'U1'),
        core.Field(u'version', u'U1'),
        core.PadByte(repeat=2),
        core.Field(u'a0UTC', u'I4'),
        core.Field(u'a1UTC', u'I4'),
        core.Field(u'dtLS', u'I1'),
        core.PadByte(repeat=1),
        core.Field(u'wnRec', u'U1'),
        core.Field(u'wnLSF', u'U1'),
        core.Field(u'dN', u'U1'),
        core.Field(u'dtLSF', u'U1'),
        core.PadByte(repeat=2),
    ]), # Input
    core.Message(0x03, u'BDS_UTC', [
        core.Field(u'type', u'U1'),
        core.Field(u'version', u'U1'),
        core.PadByte(repeat=2),
        core.Field(u'alpha0', u'I1'),
        core.Field(u'alpha1', u'I1'),
        core.Field(u'alpha2', u'I1'),
        core.Field(u'alpha3', u'I1'),
        core.Field(u'beta0', u'I1'),
        core.Field(u'beta1', u'I1'),
        core.Field(u'beta2', u'I1'),
        core.Field(u'beta3', u'I1'),
        core.PadByte(repeat=4),
    ]), # Input
    core.Message(0x80, u'DBD_POLL', [
    ]), # Poll request
    core.Message(0x80, u'DBD_IO', [
        core.PadByte(repeat=12),
        core.RepeatedBlock(u'RB', [
            core.Field(u'data',u'U1'),
        ]),
    ]),# Input/Output
    core.Message(0x02, u'GAL_EPH', [
        core.Field(u'type', u'U1'),
        core.Field(u'version', u'U1'),
        core.Field(u'svId', u'U1'),
        core.PadByte(repeat=1),
        core.Field(u'iodNav', u'U2'),
        core.Field(u'deltaN', u'I2'),
        core.Field(u'm0', u'I4'),
        core.Field(u'e', u'U4'),
        core.Field(u'sqrtA', u'U4'),
        core.Field(u'omega0', u'I4'),
        core.Field(u'i0', u'I4'),
        core.Field(u'omega', u'I4'),
        core.Field(u'omegaDot', u'I4'),
        core.Field(u'iDot', u'I2'),
        core.Field(u'cuc', u'I2'),
        core.Field(u'cus', u'I2'),
        core.Field(u'crc', u'I2'),
        core.Field(u'crs', u'I2'),
        core.Field(u'cis', u'I2'),
        core.Field(u'toe', u'U2'),
        core.Field(u'af0', u'I4'),
        core.Field(u'af1', u'I4'),
        core.Field(u'af2', u'I1'),
        core.Field(u'sisaIndexE1E5b', u'U1'),
        core.Field(u'toc', u'U2'),
        core.Field(u'bgdE1E5b', u'I2'),
        core.PadByte(repeat=2),
        core.Field(u'healthE1B', u'U1'),
        core.Field(u'dataValidityE5b', u'U1'),
        core.PadByte(repeat=4),
    ]), # Input
    core.Message(0x02, u'GAL_ALM', [
        core.Field(u'type', u'U1'),
        core.Field(u'version', u'U1'),
        core.Field(u'svId', u'U1'),
        core.PadByte(repeat=1),
        core.Field(u'ioda', u'U1'),
        core.Field(u'almWnA', u'U1'),
        core.Field(u'toa', u'U2'),
        core.Field(u'deltaSqrtA', u'I2'),
        core.Field(u'e', u'U2'),
        core.Field(u'deltaI', u'I2'),
        core.Field(u'omega0', u'I2'),
        core.Field(u'omegaDot', u'I2'),
        core.Field(u'omega', u'I2'),
        core.Field(u'm0', u'I2'),
        core.Field(u'af0', u'I2'),
        core.Field(u'healthE1B', u'U1'),
        core.Field(u'healthE5b', u'U1'),
        core.PadByte(repeat=4),
    ]), # Input
    core.Message(0x02, u'GAL_TIMEOFFSET', [
        core.Field(u'type', u'U1'),
        core.Field(u'version', u'U1'),
        core.PadByte(repeat=2),
        core.Field(u'a0G', u'I2'),
        core.Field(u'a1G', u'I2'),
        core.Field(u't0G', u'U1'),
        core.Field(u'wn0G', u'U1'),
        core.PadByte(repeat=2),
    ]), # Input
    core.Message(0x02, u'GAL_UTC', [
        core.Field(u'type', u'U1'),
        core.Field(u'version', u'U1'),
        core.PadByte(repeat=2),
        core.Field(u'a0', u'I4'),
        core.Field(u'a1', u'I4'),
        core.Field(u'dtLS', u'I1'),
        core.Field(u'tot', u'U1'),
        core.Field(u'wnt', u'U1'),
        core.Field(u'wnLSF', u'U1'),
        core.Field(u'dN', u'U1'),
        core.Field(u'dTLSF', u'I1'),
        core.PadByte(repeat=2),
    ]), # Input
])

MON_CLS = core.Cls(0x0a, u'MON', [
    core.Message(0x36, u'COMMS', [
        core.Field(u'version', u'U1'),
        core.Field(u'nPorts', u'U1'),
        core.BitField(u'txErrors', u'X1', [
            core.Flag(u'mem', 0, 1),
            core.Flag(u'alloc', 1, 2),
        ]),
        core.PadByte(repeat=0),
        core.Field(u'protIds', u'U1', 4),
        core.RepeatedBlock(u'RB', [
            core.Field(u'portId',u'U2'),
            core.Field(u'txPending',u'U2'),
            core.Field(u'txBytes',u'U4'),
            core.Field(u'txUsage',u'U1'),
            core.Field(u'txPeakUsage',u'U1'),
            core.Field(u'rxPending',u'U2'),
            core.Field(u'rxBytes',u'U4'),
            core.Field(u'rxUsage',u'U1'),
            core.Field(u'rxPeakUsage',u'U1'),
            core.Field(u'overrunErrs',u'U2'),
            core.Field(u'msgs',u'U2', 4),
            core.PadByte(repeat=7),
            core.Field(u'skipped', u'U4'),
        ]),
    ]),
    core.Message(0x28, u'GNSS', [
        core.Field(u'version', u'U1'),
        core.BitField(u'supported', u'X1', [
            core.Flag(u'GPSSup', 0, 1),
            core.Flag(u'GlonassSup', 1, 2),
            core.Flag(u'BeidouSup', 2, 3),
            core.Flag(u'GalileoSup', 3, 4),
        ]),
        core.BitField(u'defaultGnss', u'X1', [
            core.Flag(u'GPSDef', 0, 1),
            core.Flag(u'GlonassDef', 1, 2),
            core.Flag(u'BeidouDef', 2, 3),
            core.Flag(u'GalileoDef', 3, 4),
        ]),
        core.BitField(u'enabled', u'X1', [
            core.Flag(u'GPSEna', 0, 1),
            core.Flag(u'GlonasEna', 1, 2),
            core.Flag(u'BeidouEna', 2, 3),
            core.Flag(u'GalileoEna', 3, 4),
        ]),
        core.Field(u'simultaneous', u'U1'),
        core.PadByte(repeat=2),
    ]),
    core.Message(0x37, u'HW3', [ #HW and HW2 not implemented
        core.Field(u'version', u'U1'),
        core.Field(u'nPins', u'U1'),
        core.BitField(u'flags', u'X1', [
            core.Flag(u'rtcCalib', 0, 1),
            core.Flag(u'safeBoot', 1, 2),
            core.Flag(u'xtalAbsent', 2, 3),
        ]),
        core.Field(u'hwVersion', u'S', 10),
        core.PadByte(repeat=8),
        core.RepeatedBlock(u'RB', [
            core.Field(u'pinId', u'U2'),
            core.BitField(u'pinMask', u'X2', [
                core.Flag(u'periphPIO', 0, 1),
                core.Flag(u'pinBank', 1, 4),
                core.Flag(u'direction', 4, 5),
                core.Flag(u'value', 5, 6),
                core.Flag(u'vpManager', 6, 7),
                core.Flag(u'pioIrq', 7, 8),
                core.Flag(u'pioPullHigh', 8, 9),
                core.Flag(u'pioPullLow', 9, 10),
            ]),
            core.Field(u'VP', u'U1'),
            core.PadByte(repeat=0),
        ]),
    ]),
    core.Message(0x27, u'PATCH', [
        core.Field(u'version', u'U2'),
        core.Field(u'nEntries', u'U2'),
        core.RepeatedBlock(u'RB', [
            core.BitField(u'patchInfo', u'X4', [
                core.Flag(u'activated', 0, 1),
                core.Flag(u'location', 1, 3),
            ]),
            core.Field(u'comparatorNumber', u'U4'),
            core.Field(u'patchAddress', u'U4'),
            core.Field(u'patchData', u'U4'),
        ]),
    ]),
    core.Message(0x4, u'VER', [
        core.Field(u'swVersion', u'S', 30),
        core.Field(u'hwVersion', u'S', 10),
        core.RepeatedBlock(u'RB', [
            core.Field(u'extension', u'S', 30),
        ]),
    ]),
    core.Message(0x24, u'PIO', [
        core.Field(u'version', u'U1'),
        core.Field(u'responseType', u'U1'),
        core.RepeatedBlock(u'RB', [
            core.Field(u'pinState', u'U1'),
        ]),
    ]),
    core.Message(0x2b, u'PT2', [
        core.Field(u'version', u'U1'),
        core.Field(u'testmode', u'U1'),
        core.Field(u'numRfChn', u'U1'),
        core.Field(u'numSvSigDesc', u'U1'),
        core.Field(u'testRunTime', u'U4'),
        core.Field(u'clkDriftAid', u'I4'),
        core.Field(u'clkDriftTrk', u'I4'),
        core.Field(u'rtcFreq', u'U4'),
        core.Field(u'postStatus', u'U4'),
        core.RepeatedBlock(u'RB', [
            #core.Field('rfPga', 'U1'),
            core.PadByte(repeat=0), #? TODO: FIX this ... if i ever find what it is
        ]),
    ]),
    core.Message(0x38, u'RF', [
        core.Field(u'version', u'U1'),
        core.Field(u'nBlocks', u'U1'),
        core.PadByte(repeat=1),
        core.RepeatedBlock(u'RB', [
            core.Field(u'blockId', u'U1'),
            core.BitField(u'flags', u'X1', [
                core.Flag(u'jammingState', 0, 2),
            ]),
            core.Field(u'antStatus', u'U1'),
            core.Field(u'antPower', u'U1'),
            core.Field(u'postStatus', u'U4'),
            core.PadByte(repeat=3),
            core.Field(u'noisePerMS', u'U2'),
            core.Field(u'agcCnt', u'U2'),
            core.Field(u'jamInd', u'U1'),
            core.Field(u'ofsI', u'I1'),
            core.Field(u'magI', u'U1'),
            core.Field(u'ofsQ', u'I1'),
            core.Field(u'magQ', u'U1'),
            core.PadByte(repeat=2),
        ]),
    ]),
    core.Message(0x21, u'RXR', [
        core.BitField(u'flags', u'X1', [
            core.Flag(u'awake', 0, 1),
        ]),
    ]),
    core.Message(0x2f, u'SPT', [
        core.Field(u'version', u'U1'),
        core.Field(u'numSensor', u'U1'),
        core.Field(u'numRes', u'U1'),
        core.PadByte(repeat=1),
        core.RepeatedBlock(u'RB', [
            core.Field(u'sensorId', u'U1'),
            core.BitField(u'drvVer', u'X1', [
                core.Flag(u'drvVerMaj', 0, 4),
                core.Flag(u'drvVerMin', 4, 7),
            ]),
            core.Field(u'testState', u'U1'),
            core.Field(u'drvFileName', u'U1'),
        ]),
        #core.RepeatedBlock('RB2', [
        #    core.Field('sensorIdRes', 'U2'),
        #    core.Field('sensorType', 'U2'),
        #    core.Field('resType', 'U2'),
        #    core.PadByte(repeat=2),
        #    core.Field('value', 'I4'),
        #]),
    ]),
])

NAV_CLS = core.Cls(0x01, u'NAV', [
    core.Message(0x05, u'ATT', [
        core.Field(u'iTOW', u'U4'),
        core.Field(u'version', u'U1'),
        core.PadByte(repeat=1),
        core.Field(u'roll', u'I4'),
        core.Field(u'pitch', u'I4'),
        core.Field(u'heading', u'I4'),
        core.Field(u'accRoll', u'U4'),
        core.Field(u'accPitch', u'U4'),
        core.Field(u'accHeading', u'U4'),
    ]),
    core.Message(0x22, u'CLOCK', [
        core.Field(u'iTOW', u'U4'),
        core.Field(u'clkB', u'I4'),
        core.Field(u'clkD', u'I4'),
        core.Field(u'tAcc', u'U4'),
        core.Field(u'fAcc', u'U4'),
    ]),
    core.Message(0x36, u'COV', [
        core.Field(u'iTOW', u'U4'),
        core.Field(u'version', u'U1'),
        core.Field(u'posCovValid', u'U1'),
        core.Field(u'velCovValid', u'U1'),
        core.PadByte(repeat=6),
        core.Field(u'posCovNN', u'R4'),
        core.Field(u'posCovNE', u'R4'),
        core.Field(u'posCovND', u'R4'),
        core.Field(u'posCovEE', u'R4'),
        core.Field(u'posCovED', u'R4'),
        core.Field(u'posCovDD', u'R4'),
        core.Field(u'velCovNN', u'R4'),
        core.Field(u'velCovNE', u'R4'),
        core.Field(u'velCovND', u'R4'),
        core.Field(u'velCovEE', u'R4'),
        core.Field(u'velCovED', u'R4'),
        core.Field(u'velCovDD', u'R4'),
    ]),
    core.Message(0x04, u'DOP', [
        core.Field(u'iTOW', u'U4'),
        core.Field(u'gDOP', u'U2'),
        core.Field(u'pDOP', u'U2'),
        core.Field(u'tDOP', u'U2'),
        core.Field(u'vDOP', u'U2'),
        core.Field(u'hDOP', u'U2'),
        core.Field(u'nDOP', u'U2'),
        core.Field(u'eDOP', u'U2'),
    ]),
    core.Message(0x3d, u'EELL', [
        core.Field(u'iTOW', u'U4'),
        core.Field(u'version', u'U1'),
        core.Field(u'reserved', u'U1'),
        core.Field(u'errEllipseOrient', u'U2'),
        core.Field(u'errEllipseMajor', u'U4'),
        core.Field(u'errEllipseMinor', u'U4'),
    ]),
    core.Message(0x61, u'EOE', [
        core.Field(u'iTOW', u'U4'),
    ]),
    core.Message(0x39, u'GEOFENCE', [
        core.Field(u'iTOW', u'U4'),
        core.Field(u'version', u'U1'),
        core.Field(u'status', u'U1'),
        core.Field(u'numFences', u'U1'),
        core.Field(u'combState', u'U1'),
        core.RepeatedBlock(u'RB', [
            core.Field(u'state', u'U1'),
            core.Field(u'id', u'U1'),
        ]),
    ]),
    core.Message(0x13, u'HPPOSECEF', [
        core.Field(u'version', u'U1'),
        core.PadByte(repeat=1),
        core.Field(u'iTOW', u'U4'),
        core.Field(u'ecefX', u'I4'),
        core.Field(u'ecefY', u'I4'),
        core.Field(u'ecefZ', u'I4'),
        core.Field(u'ecefXHp', u'I1'),
        core.Field(u'ecefYHp', u'I1'),
        core.Field(u'ecefZHp', u'I1'),
        core.BitField(u'flags', u'X1', [
            core.Flag(u'invalidEcef', 0 ,1),
        ]),
        core.Field(u'pAcc', u'U4'),
    ]),
    core.Message(0x14, u'HPPOSLLH', [
        core.Field(u'version', u'U1'),
        core.PadByte(repeat=1),
        core.BitField(u'flags', u'X1', [
            core.Flag(u'invalidLh', 0 ,1),
        ]),
        core.Field(u'iTOW', u'U4'),
        core.Field(u'lon', u'I4'),
        core.Field(u'lat', u'I4'),
        core.Field(u'height', u'I4'),
        core.Field(u'hMSL', u'I4'),
        core.Field(u'lonHp', u'I1'),
        core.Field(u'latHp', u'I1'),
        core.Field(u'heightHp', u'I1'),
        core.Field(u'hMSLHp', u'I1'),
        core.Field(u'hAcc', u'U4'),
        core.Field(u'vAcc', u'U4'),
    ]),
    core.Message(0x34, u'ORB', [
        core.Field(u'iTOW', u'U4'),
        core.Field(u'version', u'U1'),
        core.Field(u'numSv', u'U1'),
        core.PadByte(repeat=1),
        core.RepeatedBlock(u'RB', [
            core.Field(u'gnssId', u'U1'),
            core.Field(u'svId', u'U1'),
            core.BitField(u'svFlag', u'X1', [
                core.Flag(u'health', 0, 2),
                core.Flag(u'visibility', 2, 4),
            ]),
            core.BitField(u'eph', u'X1', [
                core.Flag(u'ephUsability', 0, 5),
                core.Flag(u'ephSource', 5, 8),
            ]),
            core.BitField(u'alm', u'X1', [
                core.Flag(u'almUsability', 0, 5),
                core.Flag(u'almSource', 5, 8),
            ]),
            core.BitField(u'otherOrb', u'X1', [
                core.Flag(u'anoAopUsability', 0, 5),
                core.Flag(u'type', 5, 8),
            ]),
        ]),
    ]),
    core.Message(0x01, u'POSECEF', [
        core.Field(u'iTOW', u'U4'),
        core.Field(u'ecefX', u'I4'),
        core.Field(u'ecefY', u'I4'),
        core.Field(u'ecefZ', u'I4'),
        core.Field(u'pAcc', u'U4'),
    ]),
    core.Message(0x02, u'POSLLH', [
        core.Field(u'iTOW', u'U4'),
        core.Field(u'lon', u'I4'),
        core.Field(u'lat', u'I4'),
        core.Field(u'height', u'I4'),
        core.Field(u'hMSL', u'I4'),
        core.Field(u'hAcc', u'U4'),
        core.Field(u'vAcc', u'U4'),
    ]),
    core.Message(0x07, u'PVT', [
        core.Field(u'iTOW', u'U4'),
        core.Field(u'year', u'U2'),
        core.Field(u'month', u'U1'),
        core.Field(u'day', u'U1'),
        core.Field(u'hour', u'U1'),
        core.Field(u'min', u'U1'),
        core.Field(u'sec', u'U1'),
        core.BitField(u'valid', u'X1', [
            core.Flag(u'validDate', 0, 1),
            core.Flag(u'validTime', 1, 2),
            core.Flag(u'fullyResolved', 2, 3),
            core.Flag(u'validMag', 3, 4),
        ]),
        core.Field(u'tAcc', u'U4'),
        core.Field(u'nano', u'I4'),
        core.Field(u'fixType', u'U1'),
        core.BitField(u'flags', u'X1', [
            core.Flag(u'gnssFixOK', 0, 1),
            core.Flag(u'diffSoln', 1, 2),
            core.Flag(u'psmState', 2, 5),
            core.Flag(u'headVehValid', 5, 6),
            core.Flag(u'carrSoln', 6, 8),
        ]),
        core.BitField(u'flags2', u'X1', [
            core.Flag(u'confirmedAvai', 5, 6),
            core.Flag(u'confirmedDate', 6, 7),
            core.Flag(u'confirmedTime', 7, 8),
        ]),
        core.Field(u'numSV', u'U1'),
        core.Field(u'lon', u'I4'),
        core.Field(u'lat', u'I4'),
        core.Field(u'height', u'I4'),
        core.Field(u'hMSL', u'I4'),
        core.Field(u'hAcc', u'U4'),
        core.Field(u'vAcc', u'U4'),
        core.Field(u'velN', u'I4'),
        core.Field(u'velE', u'I4'),
        core.Field(u'velD', u'I4'),
        core.Field(u'gSpeed', u'I4'),
        core.Field(u'headMot', u'I4'),
        core.Field(u'sAcc', u'U4'),
        core.Field(u'headAcc', u'U4'),
        core.Field(u'pDOP', u'U2'),
        core.BitField(u'flags3', u'X1', [
            core.Flag(u'invalidL1h', 0, 1),
        ]),
        core.PadByte(repeat=4),
        core.Field(u'headVeh', u'I4'),
        core.Field(u'magDec', u'I2'),
        core.Field(u'magAcc', u'U2'),
    ]),
    core.Message(0x3C, u'RELPOSNED', [
        core.Field(u'version', u'U1'),
        core.PadByte(repeat=0),
        core.Field(u'refStationId', u'U2'),
        core.Field(u'iTOW', u'U4'),
        core.Field(u'relPosN', u'I4'),
        core.Field(u'relPosE', u'I4'),
        core.Field(u'relPosD', u'I4'),
        core.Field(u'relPosLength', u'I4'),
        core.Field(u'relPosHeading', u'I4'),
        core.PadByte(repeat=1),
        core.Field(u'relPosHPN', u'I1'),
        core.Field(u'relPosHPE', u'I1'),
        core.Field(u'relPosHPD', u'I1'),
        core.Field(u'relPosHPLength', u'I1'),
        core.Field(u'accN', u'U4'),
        core.Field(u'accE', u'U4'),
        core.Field(u'accD', u'U4'),
        core.Field(u'accLength', u'U4'),
        core.Field(u'accHeading', u'U4'),
        core.PadByte(repeat=1),
        core.BitField(u'flags', u'X4', [
            core.Flag(u'gnssFixOK', 0, 1),
            core.Flag(u'diffSoln', 1, 2),
            core.Flag(u'relPosValid', 2, 3),
            core.Flag(u'carrSoln', 3, 5),
            core.Flag(u'isMoving', 5, 6),
            core.Flag(u'refPosMiss', 6, 7),
            core.Flag(u'refObsMiss', 7, 8),
            core.Flag(u'relPosHeadingValid', 8, 9),
            core.Flag(u'relPosNormalized', 9, 10),
        ]),
    ]),
    core.Message(0x35, u'SAT', [
        core.Field(u'iTOW', u'U4'),
        core.Field(u'version', u'U1'),
        core.Field(u'numSvs', u'U1'),
        core.Field(u'reserved0', u'U1', 2),
        core.RepeatedBlock(u'RB', [
            core.Field(u'gnssId', u'U1'),
            core.Field(u'svId', u'U1'),
            core.Field(u'cno', u'U1'),
            core.Field(u'elev', u'I1'),
            core.Field(u'azim', u'I2'),
            core.Field(u'prRes', u'I2'),
            core.BitField(u'flags', u'X4', [
                core.Flag(u'qualityInd', 0, 3),
                core.Flag(u'svUsed', 3, 4),
                core.Flag(u'health', 4, 6),
                core.Flag(u'diffCorr', 6, 7),
                core.Flag(u'smoothed', 7, 8),
                core.Flag(u'orbitSource', 8, 11),
                core.Flag(u'ephAvail', 11, 12),
                core.Flag(u'almAvail', 12, 13),
                core.Flag(u'anoAvail', 13, 14),
                core.Flag(u'aopAvail', 14, 15),
                core.Flag(u'sbasCorrUsed', 16, 17),
                core.Flag(u'rtcmCorrUsed', 17, 18),
                core.Flag(u'slasCorrUsed', 18, 19),
                core.Flag(u'prCorrUsed', 20, 21),
                core.Flag(u'crCorrUsed', 21, 22),
                core.Flag(u'doCorrUsed', 22, 23),
            ]),
        ]),
    ]),
    core.Message(0x32, u'SBAS', [
        core.Field(u'iTOW', u'U4'),
        core.Field(u'geo', u'U1'),
        core.Field(u'mode', u'U1'),
        core.Field(u'sys', u'I1'),
        core.BitField(u'service', u'X1', [
            core.Flag(u'Ranging', 0, 1),
            core.Flag(u'Corrections', 1, 2),
            core.Flag(u'Integrity', 2, 3),
            core.Flag(u'TestMode', 3, 4),
            core.Flag(u'Bad', 4, 5),
        ]),
        core.Field(u'cnt', u'U1'),
        core.PadByte(repeat=6),
        core.RepeatedBlock(u'RB', [
            core.Field(u'svid', u'U1'),
            core.Field(u'flags', u'U1'),
            core.Field(u'udre', u'U1'),
            core.Field(u'svSys', u'U1'),
            core.Field(u'svService', u'U1'),
            core.PadByte(repeat=1),
            core.Field(u'prc', u'I2'),
            core.PadByte(repeat=2),
            core.Field(u'ic', u'I2'),
        ]),
    ]),
    core.Message(0x43, u'SIG', [ #here
        core.Field(u'iTOW', u'U4'),
        core.Field(u'version', u'U1'),
        core.Field(u'numSigs', u'U1'),
        core.PadByte(repeat=2),
        core.RepeatedBlock(u'RB', [
            core.Field(u'gnssId', u'U1'),
            core.Field(u'svId', u'U1'),
            core.Field(u'sigId', u'U1'),
            core.Field(u'freqId', u'U1'),
            core.Field(u'prRes', u'I2'),
            core.Field(u'cno', u'U1'),
            core.Field(u'qualityInd', u'U1'),
            core.Field(u'corrSource', u'U1'),
            core.Field(u'ionoModel', u'U1'),
            core.BitField(u'sigFlags', u'X2', [
                core.Flag(u'health', 0, 2),
                core.Flag(u'prSmoothed', 2, 3),
                core.Flag(u'prUsed', 3, 4),
                core.Flag(u'crUsed', 4, 5),
                core.Flag(u'doUsed', 5, 6),
                core.Flag(u'prCorrUsed', 6, 7),
                core.Flag(u'crCorrUsed', 7, 8),
                core.Flag(u'doCorrUsed', 8, 9),
            ]),
        ]),
            core.PadByte(repeat=4)
    ]),
    core.Message(0x03, u'STATUS', [
        core.Field(u'iTOW', u'U4'),
        core.Field(u'gpsFix', u'U1'),
        core.BitField(u'flags', u'X1', [
            core.Flag(u'gpsFixOK', 0, 1),
            core.Flag(u'diffSoln', 1, 2),
            core.Flag(u'wknSet', 2, 3),
            core.Flag(u'towSet', 3, 4),
        ]),
        core.BitField(u'fixStat', u'X1', [
            core.Flag(u'diffCorr', 0, 1),
            core.Flag(u'caarSolnValid', 1, 2),
            core.Flag(u'mapMatching', 6, 8),
        ]),
        core.BitField(u'flags2', u'X1', [
            core.Flag(u'psmState', 0, 2),
            core.Flag(u'spoofDetState', 3, 5),
            core.Flag(u'carSoln', 6, 8),
        ]),
        core.Field(u'ttff', u'U4'),
        core.Field(u'msss', u'U4'),
    ]),
    core.Message(0x24, u'TIMEBDS', [
        core.Field(u'iTOW', u'U4'),
        core.Field(u'SOW', u'U4'),
        core.Field(u'fSOW', u'I4'),
        core.Field(u'week', u'I2'),
        core.Field(u'leapS', u'I1'),
        core.BitField(u'valid', u'X1', [
            core.Flag(u'sowValid', 0, 1),
            core.Flag(u'weekValid', 1, 2),
            core.Flag(u'leapSValid', 2, 3),
        ]),
        core.Field(u'tAcc',u'U4'),
    ]),
    core.Message(0x25, u'TIMEGAL', [
        core.Field(u'iTOW', u'U4'),
        core.Field(u'galTow', u'U4'),
        core.Field(u'fGalTow', u'I4'),
        core.Field(u'galWno', u'I2'),
        core.Field(u'leapS', u'I1'),
        core.BitField(u'valid', u'X1', [
            core.Flag(u'galValid', 0, 1),
            core.Flag(u'galWnoValid', 1, 2),
            core.Flag(u'leapSValid', 2, 3),
        ]),
        core.Field(u'tAcc',u'U4'),
    ]),
    core.Message(0x23, u'TIMEGLO', [
        core.Field(u'iTOW', u'U4'),
        core.Field(u'TOD', u'U4'),
        core.Field(u'fTOD', u'I4'),
        core.Field(u'Nt', u'U2'),
        core.Field(u'N4', u'U1'),
        core.BitField(u'valid', u'X1', [
            core.Flag(u'todValid', 0, 1),
            core.Flag(u'dateValid', 1, 2),
        ]),
        core.Field(u'tAcc',u'U4'),
    ]),
    core.Message(0x20, u'TIMEGPS', [
        core.Field(u'iTOW', u'U4'),
        core.Field(u'fTOW', u'I4'),
        core.Field(u'week', u'I2'),
        core.Field(u'leapS', u'I1'),
        core.BitField(u'valid', u'X1', [
            core.Flag(u'towValid', 0, 1),
            core.Flag(u'weekValid', 1, 2),
            core.Flag(u'leapSValid', 2, 3),
        ]),
        core.Field(u'tAcc',u'U4'),
    ]),
    core.Message(0x25, u'TIMELS', [
        core.Field(u'iTOW', u'U4'),
        core.Field(u'version', u'U1'),
        core.PadByte(repeat=3),
        core.Field(u'srcOfCurrLs', u'U1'),
        core.Field(u'currLs', u'I1'),
        core.Field(u'srcOfLsChange', u'U1'),
        core.Field(u'lsChange', u'I1'),
        core.Field(u'timeToLsEvent', u'I4'),
        core.Field(u'dateOfLsGpsWn', u'U2'),
        core.PadByte(repeat=3),
        core.BitField(u'valid', u'X1', [
            core.Flag(u'validCurrLs', 0, 1),
            core.Flag(u'validTimeToLsEvent', 1, 2),
        ]),
    ]),
    core.Message(0x27, u'TIMEQZSS', [
        core.Field(u'iTOW', u'U4'),
        core.Field(u'qzssTow', u'U4'),
        core.Field(u'fQzssTow', u'I4'),
        core.Field(u'qzssWno', u'I2'),
        core.Field(u'leapS', u'I1'),
        core.BitField(u'valid', u'X1', [
            core.Flag(u'qzssTowValid', 0, 1),
            core.Flag(u'qzssWnoValid', 1, 2),
            core.Flag(u'leapSValid', 2, 3),
        ]),
        core.Field(u'tAcc',u'U4'),
    ]),
    core.Message(0x21, u'TIMEUTC', [
        core.Field(u'iTOW', u'U4'),
        core.Field(u'tAcc', u'U4'),
        core.Field(u'nano', u'I4'),
        core.Field(u'year', u'U2'),
        core.Field(u'month', u'U1'),
        core.Field(u'day', u'U1'),
        core.Field(u'hour', u'U1'),
        core.Field(u'min', u'U1'),
        core.Field(u'sec', u'U1'),
        core.BitField(u'valid', u'X1', [
            core.Flag(u'validTOW', 0, 1),
            core.Flag(u'validWKN', 1, 2),
            core.Flag(u'validUTC', 2, 3),
            core.Flag(u'utcStandard', 4, 8),
        ]),
    ]),
    core.Message(0x11, u'VELECEF', [
        core.Field(u'iTOW', u'U4'),
        core.Field(u'ecefVX', u'I4'),
        core.Field(u'ecefVY', u'I4'),
        core.Field(u'ecefVZ', u'I4'),
        core.Field(u'sAcc', u'U4'),
    ]),
    core.Message(0x12, u'VELNED', [
        core.Field(u'iTOW', u'U4'),
        core.Field(u'velN', u'I4'),
        core.Field(u'velE', u'I4'),
        core.Field(u'velD', u'I4'),
        core.Field(u'speed', u'U4'),
        core.Field(u'gSpeed', u'U4'),
        core.Field(u'heading', u'I4'),
        core.Field(u'sAcc', u'U4'),
        core.Field(u'cAcc', u'U4'),
    ]),
])

TIM_CLS = core.Cls(0x0D, u'TIM', [
    core.Message(0x03, u'TM2', [
        core.Field(u'ch', u'U1'),
        core.BitField(u'flags', u'X1', [
            core.Flag(u'mode', 0, 1),
            core.Flag(u'run', 1, 2),
            core.Flag(u'newFallingEdge', 2, 3),
            core.Flag(u'timeBase', 3, 5),
            core.Flag(u'utc', 5, 6),
            core.Flag(u'time', 6, 7),
            core.Flag(u'newRisingEdge', 7, 8),
        ]),
        core.Field(u'count', u'U2'),
        core.Field(u'wnR', u'U2'),
        core.Field(u'wnF', u'U2'),
        core.Field(u'towMsR', u'U4'),
        core.Field(u'towSubMsR', u'U4'),
        core.Field(u'towMsF', u'U4'),
        core.Field(u'towSubMsF', u'U4'),
        core.Field(u'accEst', u'U4'),
    ]),
    core.Message(0x01, u'TP', [
        core.Field(u'towMS', u'U4'),
        core.Field(u'towSubMS', u'U4'),
        core.Field(u'qErr', u'I4'),
        core.Field(u'week', u'U2'),
        core.BitField(u'flags', u'X1', [
            core.Flag(u'timeBase', 0, 1),
            core.Flag(u'utc', 1, 2),
            core.Flag(u'raim', 2, 4),
            core.Flag(u'qErrInvalid', 4, 5),
        ]),
        core.BitField(u'refInfo', u'X1', [
            core.Flag(u'timeRefGnss', 0, 4),
            core.Flag(u'utcStandard', 4, 8),
        ]),
    ]),
    core.Message(0x06, u'VRFY', [
        core.Field(u'itow', u'I4'),
        core.Field(u'frac', u'I4'),
        core.Field(u'deltaMs', u'I4'),
        core.Field(u'deltaNs', u'I4'),
        core.Field(u'wno', u'U2'),
        core.BitField(u'flags', u'X1', [
            core.Flag(u'src', 0, 3)
        ]),
    ]),
])
